version: '3.3'

services:
   lamp_img:
     build: ./
   lamp:
     image: dockercompose_lamp_img
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: lamp
       MYSQL_USER: lamp
       MYSQL_PASSWORD: lamp
     tty: true
     ports:
     - target: 3210
       published: 3210
       protocol: tcp
       mode: bridge
     - target: 8080
       published: 8080
       protocol: tcp
       mode: bridge

volumes:
    db_data: {}
